name: CI

env:
  DEBUG: napi:*
  APP_NAME: rust-handler-node
  MACOSX_DEPLOYMENT_TARGET: '10.13'
  CARGO_INCREMENTAL: '1'

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
      - docs/**
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm lint
      - run: cargo fmt -- --check
      - run: cargo clippy

  build:
    name: Build Windows & macOS
    strategy:
      fail-fast: false
      matrix:
        target-host:
          # macOS
          - target: x86_64-apple-darwin
            host: macos-latest
          - target: aarch64-apple-darwin
            host: macos-latest
          # Windows
          - target: x86_64-pc-windows-msvc
            host: windows-latest
          - target: aarch64-pc-windows-msvc
            host: windows-latest
    runs-on: ${{ matrix.target-host.host }}

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target-host.target }}

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/
            ~/.cargo/git/
            ~/.napi-rs
            target/
          key: cargo-${{ matrix.target-host.target }}

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build .node (Linux / macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          pnpm build --target "$TARGET" --release
        env:
          TARGET: ${{ matrix.target-host.target }}

      - name: Build .node (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          pnpm build --target ${env:TARGET} --release
        env:
          TARGET: ${{ matrix.target-host.target }}

      - name: Upload npm artifact
        shell: bash
        run: |
          mkdir -p npm/${TARGET}/bindings
          cp *.node npm/${TARGET}/bindings/
          cp index.d.ts npm/${TARGET}/
          cp package.json npm/${TARGET}/
        env:
          TARGET: ${{ matrix.target-host.target }}

      - uses: actions/upload-artifact@v5
        with:
          name: rust-handler-node-${{ matrix.target-host.target }}
          path: npm/${{ matrix.target-host.target }}

  package:
    name: Package all artifacts into single npm
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5

      # 下载 Windows & macOS artifact
      - uses: actions/download-artifact@v6
        with:
          name: rust-handler-node-x86_64-apple-darwin
          path: artifacts/x86_64-apple-darwin
      - uses: actions/download-artifact@v6
        with:
          name: rust-handler-node-aarch64-apple-darwin
          path: artifacts/aarch64-apple-darwin
      - uses: actions/download-artifact@v6
        with:
          name: rust-handler-node-x86_64-pc-windows-msvc
          path: artifacts/x86_64-pc-windows-msvc
      - uses: actions/download-artifact@v6
        with:
          name: rust-handler-node-aarch64-pc-windows-msvc
          path: artifacts/aarch64-pc-windows-msvc

      - name: Merge all into single npm package
        shell: bash
        run: |
          mkdir -p npm-package/
          for d in artifacts/*; do

            cp -r $d/bindings/* npm-package/
            cp -n $d/index.d.ts npm-package/ || true
            cp -n $d/index.js npm-package/ || true
            cp -n $d/package.json npm-package/ || true
          done

      - name: Upload final npm package
        uses: actions/upload-artifact@v5
        with:
          name: rust-handler-node-npm
          path: npm-package
