name: Rust handler node

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Run lint
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: cargo test
        run: cargo test

      - name: Build rust handler node by napi
        run: pnpm --filter rust-handler-node build
        working-directory: packages/rust-handler-node

      - name: Build rust handler node by node
        run: pnpm run build
        working-directory: packages/rust-handler-node

  test-binding:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: macos-latest
            target: aarch64-apple-darwin
          - host: windows-latest
            build: pnpm test
            target: x86_64-pc-windows-msvc

    name: stable / ${{ matrix.settings.target }} / node@${{ matrix.node-version }}
    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - uses: dtolnay/rust-toolchain@stable
        if: ${{ !contains(matrix.settings.build, 'cmake-js') }}
        with:
          targets: ${{ matrix.settings.target }}

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build rust handler node by napi
        run: pnpm --filter rust-handler-node build --platform --release --target ${{ matrix.settings.target }}
        working-directory: packages/rust-handler-node

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: packages/rust-handler-node/*.node
          if-no-files-found: error

  test-binding-linux:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - host: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - host: ubuntu-latest
            target: armv7-unknown-linux-musleabihf

    name: stable / ${{ matrix.settings.target }} / node@${{ matrix.node-version }}

    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.target }}

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build rust handler node by napi with x86_64-unknown-linux-gnu
        if: ${{ matrix.settings.target == 'x86_64-unknown-linux-gnu' }}
        run: pnpm --filter rust-handler-node build --platform --release --target ${{ matrix.settings.target }}
        working-directory: packages/rust-handler-node

      - name: Download cross ${runner.os}-${{ matrix.settings.target }} binary tar balls
        if: ${{ matrix.settings.target != 'x86_64-unknown-linux-gnu' }}
        uses: robinraju/release-downloader@v1
        with:
          repository: 'tn-linux/cross'
          latest: true
          fileName: '*x86_64-unknown-linux-musl-$*-${{ matrix.settings.target }}*'

      - name: Install cross
        run: |
          chmod +x ./*x86_64-unknown-linux-musl-*-${{ matrix.settings.target }}*
          sudo cp ./*x86_64-unknown-linux-musl-*-${{ matrix.settings.target }}* /usr/local/bin/cross

      - name: Check cross
        run: cross --version

      - name: Build rust handler node by napi with cross
        if: ${{ matrix.settings.target != 'x86_64-unknown-linux-gnu' }}
        run: cross build --release --target ${{ matrix.settings.target }}
        working-directory: packages/rust-handler-node

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: |
            packages/rust-handler-node/*.node
            packages/rust-handler-node/target/${{ matrix.settings.target }}/release/*.so
          if-no-files-found: error

  test-wasi:
    name: stable / wasi / node@${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        s:
          - wasi-profile: command-wasi
            wasi-target: wasm32-wasip1-threads
          - wasi-profile: command-wasi-preview1
            wasi-target: wasm32-wasip1-threads

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - uses: dtolnay/rust-toolchain@1.79.0
        with:
          targets: ${{ matrix.s.wasi-target }}

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build wasm by napi
        run: cargo build --release --target ${{ matrix.s.wasi-target }} --profile ${{ matrix.s.wasi-profile }}
        working-directory: packages/rust-handler-node

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.s.wasi-target }}-${{ matrix.s.wasi-profile }}
          path: packages/rust-handler-node/target/${{ matrix.s.wasi-target }}/release/${{ matrix.s.wasi-profile }}/*.wasm
          if-no-files-found: error

  publish:
    needs: [build, test-binding, test-binding-linux, test-wasi]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Download all artefact
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Move artifact
        run: pnpm --filter rust-handler-node artifacts
        working-directory: packages/rust-handler-node

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: node scripts/publish.mjs

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
